### ISSUE TITLE
Unknown Emoji Error

### ISSUE THREAD

**Issue by zuifiti** [reinhello/eris-giveaways#92]
the error: (on giveaway start)

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

DiscordRESTError [10014]: Unknown Emoji
    at RequestHandler.request (/home/runner/uriel/node_modules/eris/lib/rest/RequestHandler.js:75:15)
    at Gaby.addMessageReaction (/home/runner/uriel/node_modules/eris/lib/Client.js:308:36)
    at Message.addReaction (/home/runner/uriel/node_modules/eris/lib/structures/Message.js:393:48)
    at /home/runner/uriel/node_modules/eris-giveaways/src/Manager.js:477:27
```

my code: 

```
const manager = new GiveawaysManager(client, {
    storage: "./giveaways.json",
    default: {
        botsCanWin: false,
        embedColor: 0x0380EC,
        embedColorEnd: 0x0380EC,
        reaction: "🎉",
        lastChance: {
          enabled: true,
          content: `O tempo está acabando!`,
          threshold: 11000,
          embedColor: 0x0380EC
        }
    }
});
```

**Comment by reinhello** [comment]
Seems right to me. May I see your `manager.start()` code?
